### ISSUE TITLE
How-to source?

### ISSUE THREAD

**Issue by carlosperate** [microbit-playground/microbit-playground.github.io#14]
I had a look in this repository and the others under the github organisation but couldn't find them.
I assumed they would be markdown files in their own repository like https://github.com/microbit-playground/blog-posts ?

**Comment by jezdean** [comment]
It's still to go up. `blog-posts`, `components` and `programs` are up. There's `how to` and a few others still go.

**Comment by carlosperate** [comment]
Oh, okay, thanks for the clarification! I'll close this then.

**Comment by jezdean** [comment]
This now up at [https://github.com/microbit-playground/howto]( this repo) 

(https://github.com/microbit-playground/howto)[repo]

**Comment by jezdean** [comment]
(https://github.com/microbit-playground/howto)[repo]

[https://github.com/microbit-playground/howto](repo)

**Comment by jezdean** [comment]
okay it's here: https://github.com/microbit-playground/howto

😆

**Comment by carlosperate** [comment]
Awesome, thanks Jez!
