### ISSUE TITLE
The Python code in the logomasters.svg image is wrong. :-)

### ISSUE THREAD

**Issue by ntoll** [microbit-playground/microbit-playground.github.io#2]
It should be:

```
from microbit import *
display.scroll("Hello, World!")
```

You don't need to do `microbit.display.scroll` since that'll cause an error. ;-)

**Comment by jezdean** [comment]
Thanks @ntoll. I really hope no one else spotted that! I've ~~fixed~~ hid the mistake :joy: 

![terrible-fix](https://cloud.githubusercontent.com/assets/1617013/13630523/4e364678-e612-11e5-8543-944b74a5ec1f.png)

**Comment by ntoll** [comment]
Exactly, path of least resistance and all that. ;-)
